2023-11-06 20:14:07 - Erro durante o processo de cadastro: Incorrect result size: expected 1, actual 0
2023-11-06 20:18:45 - Erro durante o processo de cadastro: Incorrect result size: expected 1, actual 0
2023-11-06 20:20:32 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (uso, frequencia, data_captura, fk_componente) VALUES (?, ?, ?, ?)]; Data truncation: Out of range value for column 'frequencia' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'frequencia' at row 1
2023-11-06 20:20:33 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (uso, frequencia, data_captura, fk_componente) VALUES (?, ?, ?, ?)]; Data truncation: Out of range value for column 'frequencia' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'frequencia' at row 1
2023-11-06 20:20:43 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (uso, frequencia, data_captura, fk_componente) VALUES (?, ?, ?, ?)]; Data truncation: Out of range value for column 'frequencia' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'frequencia' at row 1
2023-11-06 20:20:53 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (uso, frequencia, data_captura, fk_componente) VALUES (?, ?, ?, ?)]; Data truncation: Out of range value for column 'frequencia' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'frequencia' at row 1
2023-11-06 20:21:03 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (uso, frequencia, data_captura, fk_componente) VALUES (?, ?, ?, ?)]; Data truncation: Out of range value for column 'frequencia' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'frequencia' at row 1
2023-11-06 20:21:13 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (uso, frequencia, data_captura, fk_componente) VALUES (?, ?, ?, ?)]; Data truncation: Out of range value for column 'frequencia' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'frequencia' at row 1
2023-11-06 20:21:23 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (uso, frequencia, data_captura, fk_componente) VALUES (?, ?, ?, ?)]; Data truncation: Out of range value for column 'frequencia' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'frequencia' at row 1
2023-11-06 20:21:33 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (uso, frequencia, data_captura, fk_componente) VALUES (?, ?, ?, ?)]; Data truncation: Out of range value for column 'frequencia' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'frequencia' at row 1
2023-11-06 20:21:43 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (uso, frequencia, data_captura, fk_componente) VALUES (?, ?, ?, ?)]; Data truncation: Out of range value for column 'frequencia' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'frequencia' at row 1
2023-11-06 20:21:53 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (uso, frequencia, data_captura, fk_componente) VALUES (?, ?, ?, ?)]; Data truncation: Out of range value for column 'frequencia' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'frequencia' at row 1
2023-11-06 20:22:03 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (uso, frequencia, data_captura, fk_componente) VALUES (?, ?, ?, ?)]; Data truncation: Out of range value for column 'frequencia' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'frequencia' at row 1
2023-11-06 20:22:13 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (uso, frequencia, data_captura, fk_componente) VALUES (?, ?, ?, ?)]; Data truncation: Out of range value for column 'frequencia' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'frequencia' at row 1
2023-11-06 20:22:23 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (uso, frequencia, data_captura, fk_componente) VALUES (?, ?, ?, ?)]; Data truncation: Out of range value for column 'frequencia' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'frequencia' at row 1
2023-11-06 20:22:33 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (byte_leitura, leituras, byte_escrita, escritas, data_captura, fk_componente) VALUES (?, ?, ?, ?, ?, ?)]; Data truncation: Out of range value for column 'byte_leitura' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'byte_leitura' at row 1
2023-11-06 20:22:43 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (byte_leitura, leituras, byte_escrita, escritas, data_captura, fk_componente) VALUES (?, ?, ?, ?, ?, ?)]; Data truncation: Out of range value for column 'byte_leitura' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'byte_leitura' at row 1
2023-11-06 20:23:26 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (byte_leitura, leituras, byte_escrita, escritas, data_captura, fk_componente) VALUES (?, ?, ?, ?, ?, ?)]; Data truncation: Out of range value for column 'byte_leitura' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'byte_leitura' at row 1
2023-11-06 20:23:33 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (byte_leitura, leituras, byte_escrita, escritas, data_captura, fk_componente) VALUES (?, ?, ?, ?, ?, ?)]; Data truncation: Out of range value for column 'byte_leitura' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'byte_leitura' at row 1
2023-11-06 20:23:43 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (byte_leitura, leituras, byte_escrita, escritas, data_captura, fk_componente) VALUES (?, ?, ?, ?, ?, ?)]; Data truncation: Out of range value for column 'byte_escrita' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'byte_escrita' at row 1
2023-11-06 20:23:53 - Erro ao capturar e salvar dados de memória: PreparedStatementCallback; SQL [INSERT INTO dados_captura (byte_leitura, leituras, byte_escrita, escritas, data_captura, fk_componente) VALUES (?, ?, ?, ?, ?, ?)]; Data truncation: Out of range value for column 'byte_escrita' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Out of range value for column 'byte_escrita' at row 1
2023-11-07 19:53:13 - Erro durante o processo de login: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'root'@'localhost' (using password: YES))
2023-11-07 19:53:40 - Erro durante o processo de login: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'root'@'localhost' (using password: YES))
2023-11-07 19:55:21 - Erro durante o processo de login: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (Unknown database 'yott')
2023-11-07 20:04:33 - Erro durante o processo de login: Incorrect result size: expected 1, actual 0
